buckets:
  dev: nrl-data-dev
  prod: nrl-data-prod

urls:
  main: https://www.nrl.com
  draw: draw

competition_code_map:
  nrl: '111'
  nrlw: '161'
  knockon: '113'
  hostplus: '114'
  preseason: '119'

feature_pipeline:
  - win_loss_draw
  - spine_team
  - win_loss_draw_full
  - features_team
  - labels
  - train

# teams:
#   - Broncos
#   - Roosters
#   - Wests Tigers
#   - Rabbitohs
#   - Storm
#   - Eels
#   - Raiders
#   - Knights
#   - Dragons
#   - Sea Eagles
#   - Panthers
#   - Sharks
#   - Bulldogs
#   - Dolphins
#   - Titans
#   - Cowboys
#   - Warriors

# nrl_website: "https://www.nrl.com/draw/nrl-premiership/"
# nrlw_website: "https://www.nrl.com/draw/womens-premiership/"
# hostplus_website: "https://www.qrl.com.au/draw/qrl-premiership/"
# knockon_website: "https://www.nswrl.com.au/draw/nsw-cup/"
# # data_website: "https://geo145327-staging.s3.ap-southeast-2.amazonaws.com/public/"

# player_labels:
#   - Number
#   - Position
#   - Mins Played
#   - Points
#   - Tries
#   - Conversions
#   - Conversion Attempts
#   - Penalty Goals
#   - Goal Conversion Rate
#   - 1 Point Field Goals
#   - 2 Point Field Goals
#   - Total Points
#   - All Runs
#   - All Run Metres
#   - Kick Return Metres
#   - Post Contact Metres
#   - Line Breaks
#   - Line Break Assists
#   - Try Assists
#   - Line Engaged Runs
#   - Tackle Breaks
#   - Hit Ups
#   - Play The Ball
#   - Average Play The Ball Speed
#   - Dummy Half Runs
#   - Dummy Half Run Metres
#   - One on One Steal
#   - Offloads
#   - Dummy Passes
#   - Passes
#   - Receipts
#   - Passes To Run Ratio
#   - Tackle Efficiency
#   - Tackles Made
#   - Missed Tackles
#   - Ineffective Tackles
#   - Intercepts
#   - Kicks Defused
#   - Kicks
#   - Kicking Metres
#   - Forced Drop Outs
#   - Bomb Kicks
#   - Grubbers
#   - 40/20
#   - 20/40
#   - Cross Field Kicks
#   - Kicked Dead
#   - Errors
#   - Handling Errors
#   - One on One Lost
#   - Penalties
#   - Ruck Infringements
#   - Inside 10 Metres
#   - On Report
#   - Sin Bins
#   - Send Offs
#   - Stint One
#   - Stint Two

# nrl_2024_round: 1

# team_colours:
#   Broncos: "#760135"
#   Roosters: "#e82c2e"
#   Wests Tigers: "#f68b1f"
#   Rabbitohs: "#006633"
#   Storm: "#3E2783"
#   Eels: "#ffd327"
#   Raiders: "#c3d941"
#   Knights: "#ee3524"
#   Dragons: "#e2231b"
#   Sea Eagles: "#6F0F3B"
#   Panthers: "#221F20"
#   Sharks: "#00a9d8"
#   Bulldogs: "#0054A4"
#   Dolphins: "#E5CC7A"
#   Titans: "#e7a614"
#   Cowboys: "#002b5c"
#   Warriors: "#231f20"

# team_colours_inverse:
#   Broncos: "#fbbf15"
#   Roosters: "#00305e"
#   Wests Tigers: "#000000"
#   Rabbitohs: "#e2261b"
#   Storm: "#f9b018"
#   Eels: "#006eb5"
#   Raiders: "#00ac5b"
#   Knights: "#00539f"
#   Dragons: "#ffffff"
#   Sea Eagles: "#ffffff"
#   Panthers: "#ff0082"
#   Sharks: "#000000"
#   Bulldogs: "#A7A9AC"
#   Dolphins: "#FB141E"
#   Titans: "#009ddc"
#   Cowboys: "#ffdd00"
#   Warriors: "#bdbcbc"

# nrlw_teams:
#   - Broncos
#   - Roosters
#   - Wests Tigers
#   - Eels
#   - Raiders
#   - Knights
#   - Dragons
#   - Sharks
#   - Titans
#   - Cowboys

# hostplus_teams:
#   - Falcons
#   - Devils
#   - Dolphins
#   - WM Seagulls
#   - Blackhawks
#   - Seagulls
#   - Jets
#   - Tigers
#   - Capras
#   - Pride
#   - Cutters
#   - Bears
#   - Magpies
#   - Hunters
#   - Clydesdales

# knockon_teams:
#   - Dragons
#   - Jets
#   - Warriors
#   - Eels
#   - Knights
#   - Panthers
#   - Bulldogs
#   - Raiders
#   - Rabbitohs
#   - Roosters
#   - Sea Eagles
#   - Bears
#   - Magpies
