name: Create gcp.env file
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "USERNAME=${{ secrets.USERNAME }}" > gcp.env
        echo "PROJECT=${{ vars.PROJECT }}" >> gcp.env
        echo "REGION=${{ vars.REGION }}" >> gcp.env

        echo "DOCKER_REPO=${{ vars.DOCKER_REPO }}" >> gcp.env
        echo "SVC_ACCT=${{ vars.SVC_ACCT }}" >> gcp.env
        echo "SVC_EMAIL=${{ secrets.SVC_EMAIL }}" >> gcp.env

        echo "SCRAPER_SVC_ACCT=${{ vars.SCRAPER_SVC_ACCT }}" >> gcp.env
        echo "SCRAPER_SVC_EMAIL=${{ secrets.SCRAPER_SVC_EMAIL }}" >> gcp.env
        echo "DEV_BUCKET=${{ vars.DEV_BUCKET }}" >> gcp.env
        echo "PROD_BUCKET=${{ vars.PROD_BUCKET }}" >> gcp.env
        echo "SCRAPER_IMAGE=${{ vars.SCRAPER_IMAGE }}" >> gcp.env
        echo "SCRAPER_JOB_DEV=${{ vars.SCRAPER_JOB_DEV }}" >> gcp.env
        echo "SCRAPER_SCHEDULE_NAME_DEV=${{ vars.SCRAPER_SCHEDULE_NAME_DEV }}" >> gcp.env
        echo "SCRAPER_JOB_PROD=${{ vars.SCRAPER_JOB_PROD }}" >> gcp.env
        echo "SCRAPER_SCHEDULE_NAME_PROD=${{ vars.SCRAPER_SCHEDULE_NAME_PROD }}" >> gcp.env
