# scraper cloud run job

include .env
export

SERVICE=$(FEATENG_SERVICE)
IMAGE=$(FEATENG_IMAGE)
CONTAINER_NAME=$(FEATENG_SERVICE)-container
JOB_DEV=$(FEATENG_JOB_DEV)
JOB_PROD=$(FEATENG_JOB_PROD)
SCHEDULE_NAME_DEV=$(FEATENG_SCHEDULE_NAME_DEV)
SCHEDULE_NAME_PROD=$(FEATENG_SCHEDULE_NAME_PROD)

include make/cloud_run_job.mk
