# scraper cloud run job

include .env
export

FOLDER=$(SCRAPER_FOLDER)
IMAGE=$(SCRAPER_IMAGE)
CONTAINER_NAME=$(SCRAPER_FOLDER)_container
JOB_DEV=$(SCRAPER_JOB_DEV)
JOB_PROD=$(SCRAPER_JOB_PROD)
SCHEDULE_NAME_DEV=$(SCRAPER_SCHEDULE_NAME_DEV)
SCHEDULE_NAME_PROD=$(SCRAPER_SCHEDULE_NAME_PROD)

include make/cloud_run_job.mk
